ame: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # For Render deployment
      - name: Deploy to Render
        if: ${{ vars.DEPLOYMENT_PLATFORM == 'render' }}
        run: |
          curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      # For DigitalOcean deployment
      - name: Deploy to DigitalOcean
        if: ${{ vars.DEPLOYMENT_PLATFORM == 'digitalocean' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /root/your_project_directory
            git pull
            docker compose down
            docker compose up -d --build