version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY}/hotel-management-api:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-5000}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE:-30d}
      - JWT_COOKIE_EXPIRE=${JWT_COOKIE_EXPIRE:-30}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - CORS_ORIGIN_PROD=${CORS_ORIGIN_PROD}
      # Add any other environment variables needed
    networks:
      - hotel-network
    # For production, you might want to add health checks
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-5000}/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hotel-network:
    driver: bridge