version: '3.8'

services:
  api:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/hotel-booking
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=30d
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - hotel-network 

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - hotel-network

volumes:
  mongo-data:

networks:
  hotel-network:
    driver: bridge